CREATE TABLE users (
id INTEGER PRIMARY KEY AUTO_INCREMENT,
Username VARCHAR(100) NOT NULL,
email VARCHAR(255) NOT NULL UNIQUE,
hash_password VARCHAR(255) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE categories (
id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
NAME VARCHAR(255),
user_id INTEGER NOT NULL,
FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE transactions (
id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
category_id INTEGER NOT NULL,
transaction_type ENUM('INCOME', 'EXPENSE') NOT NULL,
amount DECIMAL(10,2),
DESCRIPTION TEXT,
CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (category_id) REFERENCES categories(id)
);
